apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fortune-mysql
  name: fortune-mysql
  namespace: default
spec:
  selector:
    matchLabels:
      app: fortune-mysql
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate    
  replicas: 1
  template:
    metadata:
      labels:
        app: fortune-mysql
    spec:
      containers:
        - name: fortune-mysql
          image: 865868102637.dkr.ecr.us-east-2.amazonaws.com/fortune-aws:1.0.0
          imagePullPolicy: IfNotPresent
          resources:
            requests: 
              cpu: "250m"
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  host

            - name: DB_NAME  # Setting Database name from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  dbNameFortune

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  password
---
# Define a 'Service' To Expose the application
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fortune-mysql
  name: fortune-mysql
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 8100    # Port inside the cluster
      targetPort: 8100   # Port exposed to the outside
  selector:
    app: fortune-mysql
  sessionAffinity: None
  type: LoadBalancer