apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: fortune-service
  name: fortune-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortune-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fortune-service
    spec:
      containers:
      - image: nikoleye/fortune-service:1.0.0-MYSQL
        imagePullPolicy: IfNotPresent
        name: fortune-service
        resources:
          requests: 
            cpu: "250m"
        env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              value: mysql

            - name: DB_NAME  # Setting Database name from configMap
              value: fortune_dir

            - name: DB_USERNAME  # Setting Database username from Secret
              value: root

            - name: DB_PASSWORD # Setting Database password from Secret
              value: root
      restartPolicy: Always            
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: fortune-service
  name: fortune-service
  namespace: default
spec:
  ports:
  -  port: 8000
     protocol: TCP
     targetPort: 8000
  selector:
    app: fortune-service
  sessionAffinity: None
  type: LoadBalancer